name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        NODE_VERSION: [12.x]

    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'master'

      - name: Use Node.js ${{ matrix.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test